"""add credit and phone_number to users

Revision ID: c43dbdcaf7c8
Revises: 123787591292
Create Date: 2026-05-30 18:32:08.862147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43dbdcaf7c8'
down_revision: Union[str, Sequence[str], None] = '123787591292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credit', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), server_default='NOT_SET', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'credit')
    # ### end Alembic commands ###
